# monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics

  # Agent Memory Backend API 모니터링
  - job_name: 'agent-memory-backend'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['backend:8100']
    metrics_path: /metrics
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: backend:8100

  # Frontend 애플리케이션 모니터링
  - job_name: 'agent-memory-frontend'
    scrape_interval: 30s
    static_configs:
      - targets: ['frontend:8501']
    metrics_path: /metrics
    honor_labels: true

  # Redis 모니터링 (Redis Exporter 사용)
  - job_name: 'redis'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.+)'
        replacement: 'redis:6380'

  # Neo4j 모니터링
  - job_name: 'neo4j'
    scrape_interval: 30s
    static_configs:
      - targets: ['neo4j:2004']
    metrics_path: /metrics
    basic_auth:
      username: 'neo4j'
      password: 'password'
    honor_labels: true

  # ChromaDB 모니터링 (커스텀 exporter)
  - job_name: 'chromadb'
    scrape_interval: 30s
    static_configs:
      - targets: ['chromadb:8000']
    metrics_path: /api/v1/heartbeat
    honor_labels: true

  # Node Exporter (시스템 메트릭)
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']
    honor_labels: true

  # cAdvisor (컨테이너 메트릭)
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
    honor_labels: true
    relabel_configs:
      - source_labels: [__name__]
        regex: 'container_.*'
        target_label: __name__
        replacement: '${1}'

  # Agent 성능 메트릭 (커스텀 exporter)
  - job_name: 'agent-performance'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend:8100']
    metrics_path: /api/v1/performance/metrics
    honor_labels: true
    params:
      format: ['prometheus']

  # Memory System 메트릭
  - job_name: 'memory-system'
    scrape_interval: 15s
    static_configs:
      - targets: ['backend:8100']
    metrics_path: /api/v1/memory/metrics
    honor_labels: true

  # Feedback System 메트릭
  - job_name: 'feedback-system'
    scrape_interval: 20s
    static_configs:
      - targets: ['backend:8100']
    metrics_path: /api/v1/feedback/metrics
    honor_labels: true

  # MCP Tools 모니터링
  - job_name: 'mcp-tools'
    scrape_interval: 15s
    static_configs:
      - targets: ['backend:8100']
    metrics_path: /api/v1/mcp/metrics
    honor_labels: true
    scrape_configs:
      - job_name: 'mcp-tools-detailed'
        scrape_interval: 30s
        static_configs:
          - targets: ['backend:8100']
        metrics_path: /api/v1/mcp/tools/metrics
        honor_labels: true

  # API Gateway 메트릭 (만약 사용 중이라면)
  - job_name: 'api-gateway'
    scrape_interval: 15s
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: /metrics
    honor_labels: true

# Remote write 설정 (선택사항 - 외부 시계열 DB로 전송)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "your_username"
#       password: "your_password"

# Remote read 설정 (선택사항 - 외부 시계열 DB에서 읽기)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"
#     basic_auth:
#       username: "your_username"
#       password: "your_password"

# 저장 설정
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
    wal-compression: true

# 서버 설정
server:
  http_listen_port: 9090
  grpc_listen_port: 9095
  
# 로그 설정
log_level: info
log_format: json

# Feature flags
feature_flags:
  - enable-feature=remote-write-receiver
  - enable-feature=exemplar-storage

# Web 인터페이스 설정
web:
  console:
    libraries: /usr/share/prometheus/console_libraries
    templates: /usr/share/prometheus/consoles
  enable-lifecycle: true
  enable-admin-api: true
  max-connections: 512
  read-timeout: 30s

# 추가 설정: 서비스 디스커버리 (Kubernetes 환경용)
# - job_name: 'kubernetes-apiservers'
#   kubernetes_sd_configs:
#   - role: endpoints
#   scheme: https
#   tls_config:
#     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#   relabel_configs:
#   - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
#     action: keep
#     regex: default;kubernetes;https

# - job_name: 'kubernetes-nodes'
#   kubernetes_sd_configs:
#   - role: node
#   scheme: https
#   tls_config:
#     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#   relabel_configs:
#   - action: labelmap
#     regex: __meta_kubernetes_node_label_(.+)

# - job_name: 'kubernetes-pods'
#   kubernetes_sd_configs:
#   - role: pod
#   relabel_configs:
#   - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#     action: keep
#     regex: true
#   - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
#     action: replace
#     target_label: __metrics_path__
#     regex: (.+)
#   - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
#     action: replace
#     regex: ([^:]+)(?::\d+)?;(\d+)
#     replacement: $1:$2
#     target_label: __address__
#   - action: labelmap
#     regex: __meta_kubernetes_pod_label_(.+)
#   - source_labels: [__meta_kubernetes_namespace]
#     action: replace
#     target_label: kubernetes_namespace
#   - source_labels: [__meta_kubernetes_pod_name]
#     action: replace
#     target_label: kubernetes_pod_name

# Agent Memory 시스템 특화 설정
recording_rules:
  - name: agent_memory_rules
    interval: 30s
    rules:
      # 응답 시간 관련 규칙
      - record: agent:response_time:rate5m
        expr: rate(request_duration_seconds_sum[5m]) / rate(request_duration_seconds_count[5m])
      
      # 메모리 사용량 관련 규칙
      - record: agent:memory_usage:rate5m
        expr: rate(memory_operations_total[5m])
      
      # 에러율 관련 규칙
      - record: agent:error_rate:rate5m
        expr: rate(requests_total{status=~"5.."}[5m]) / rate(requests_total[5m])
      
      # 처리량 관련 규칙
      - record: agent:throughput:rate1m
        expr: rate(requests_total[1m])

  - name: system_health_rules
    interval: 60s
    rules:
      # CPU 사용률
      - record: system:cpu_usage:avg5m
        expr: avg(rate(cpu_seconds_total[5m])) by (instance)
      
      # 메모리 사용률
      - record: system:memory_usage:current
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
      
      # 디스크 사용률
      - record: system:disk_usage:current
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100

# 알림 규칙 (별도 rules 디렉토리에서 관리)
alerting_rules:
  - name: agent_memory_alerts
    rules:
      # 높은 응답 시간 알림
      - alert: HighResponseTime
        expr: agent:response_time:rate5m > 5
        for: 2m
        labels:
          severity: warning
          service: agent-memory
        annotations:
          summary: "High response time detected"
          description: "Response time is {{ $value }}s for {{ $labels.instance }}"
      
      # 높은 에러율 알림
      - alert: HighErrorRate
        expr: agent:error_rate:rate5m > 0.1
        for: 5m
        labels:
          severity: critical
          service: agent-memory
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"
      
      # 메모리 시스템 오류 알림
      - alert: MemorySystemDown
        expr: up{job="agent-memory-backend"} == 0
        for: 1m
        labels:
          severity: critical
          service: agent-memory
        annotations:
          summary: "Agent Memory Backend is down"
          description: "The agent memory backend service is not responding"
      
      # 높은 시스템 리소스 사용률 알림
      - alert: HighCPUUsage
        expr: system:cpu_usage:avg5m > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
      
      - alert: HighMemoryUsage
        expr: system:memory_usage:current > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"